Repository ppy/osu-performance, pull requests merged in 2020-12, with the labels that each got.

#126 Use Microsoft's msbuild setup action
  .github/workflows/main.yml
Labels: size/XS

#125 Port xexxar's AR11 nerf changes
  src/performance/osu/OsuScore.cpp
Labels: size/M

#110 Change SO pp multiplier to be based on amount of spinners in the map
  include/pp/performance/Beatmap.h
  include/pp/performance/osu/OsuScore.h
  src/performance/Processor.cpp
  src/performance/osu/OsuScore.cpp
Labels: size/S

#130 Fix linux ci build
  .github/workflows/main.yml
Labels: size/XS

#129 Port xexxar's miss curve changes
  src/performance/osu/OsuScore.cpp
Labels: size/S

#128 Port xexxar's low accuracy speed nerf
  src/performance/osu/OsuScore.cpp
Labels: size/XS

#127 [osu!std] Change NF multiplier to be based on amount of misses
  src/performance/osu/OsuScore.cpp
Labels: size/XS
